ironcalc/IronCalc

.github/workflows/deploy-cargo-docs.yaml, .github/workflows/rust-build-test.yaml, Makefile, base/src/actions.rs, xlsx/src/lib.rs
This PR adds some additional code documentation to `base/src/actions.rs` and adds 2 new GitHub Actions.  Those GitHub Actions are responsible for:
1. Building, testing, and linting the repository when any pushes or PRs occur on the `main` branch.  This will ensure that any failing tests are caught before being pushed.
2. Automatically uploading documentation generated by `cargo doc --no-deps` to GitHub Pages to serve as a static website.  This will allow contributors to quickly view up-to-date documentation.
In order to get GitHub Pages to serve the new documentation that is being pushed to the `gh-pages` branch, we need to also:
1. Go to the "Pages" section for the repository's settings on GitHub.
2. Select the `gh-pages` branch as the source for the GitHub Pages site.
3. Save the …
=> Adding GitHub Actions for building/testing/linting and deploying code documentation

base/src/actions.rs
A change went in as part of https://github.com/ironcalc/IronCalc/pull/1 that is causing [the build to fail](https://github.com/ironcalc/IronCalc/actions/runs/7818740638/job/21329619681).  This fixes the formatting issue.
Formatting issues should be caught before being merged in the future as part of https://github.com/ironcalc/IronCalc/blob/main/.github/workflows/rust-build-test.yaml#L22-L23.
=> Fixing formatting issue that is causing the build to fail

base/src/expressions/lexer/test/test_common.rs
Adding additional unit tests for the lexer in order to beef up code coverage according to https://app.codecov.io/gh/ironcalc/IronCalc/blob/main/base%2Fsrc%2Fexpressions%2Ftoken.rs.
=> Adding additional lexer unit tests

xlsx/src/export/test/test_export.rs, xlsx/src/export/worksheets.rs, xlsx/tests/test.rs
What is the enhancement ?
>> Currently the project can only load the merged cells from xlsx file, exporting the merged cells was not supported. This PR addresses this issue.
How it has been done ?
>> Small patch of code has been added to _get_worksheet_xml_ function where we export the merged cells in xml.
What is the UT ?
>> Testcase covers the basic scenario where, we load the already existed xlsx file ( containing the merged cell ) and we export the same file to different name. Later we compare the xml block of each files and validate.
=> Exporting the Merged Cell : Exports the merged cell properly with testcase to verify the scenario

docs/src/programming/about.md
Um. Needs no explanation. That "tat" should be that "that" you see.
=> Style: fix typo tat to that

docs/README.md
Updated the README.md file in the docs folder to clarify that the _npm install_ command should be executed in the _docs_ folder. Also fixed a couple of trivial typos.
=> Minor update to the README file in docs.

base/src/expressions/parser/mod.rs, base/src/expressions/parser/test_issue_155.rs, base/src/test/mod.rs, base/src/test/test_issue_155.rs
Fixes #155
This is a bit weird, as it will do some transformations like:
D2:A20 => A2:D20
But at least does not transform valid ranges
=> FIX[parser]: Check the order (row, column) in range before transforming

webapp/src/components/toolbar.tsx
Hey @nhatcher,
As discussed, I've moved the border button in the toolbox next to the fill background button.
Before:
After:
Thanks!
D
=> UPDATE: Moved Border button next to Background color button

base/src/user_model/common.rs
Running `make test` fails on a clippy lint:
Rectify the lint as suggested by clippy.
=> Fix clippy lint

webapp/src/components/navigation/navigation.tsx
Hi!
Last PR today. I've added some horizontal scrolling to the spreadsheet navigator. Until now it was impossible to reach all sheets when the screen gets too narrow and/or there are way too many sheets. See below the difference:
Before (sorry, for some reason the video is uploaded as attachment):
https://github.com/user-attachments/assets/b1ab681d-b671-4d73-9cdc-927a75e58d23
After:
https://github.com/user-attachments/assets/df8ef324-de0a-4045-af24-d6ad54a35156
Best,
D
=> FIX: Makes footer/navigator scrollable when there are too many sheets

webapp/src/components/formatMenu.tsx
Hi again,
I've also made some cosmetic adjustments in the Format Menu, so it looks as expected. See the difference below:
Before:
After:
Best,
D
=> FIX: Makes styling in Format Menu consistent with Figmas

webapp/src/components/formatPicker.tsx
Hi there,
I've made some changes in the Custom Format dialog to make them more consistent with the rest of the app. See below what has changed:
Before:
After:
Let me know what you think. 
Thanks,
D
=> FIX: Makes styling in Format Dialog consistent with Figmas

webapp/src/components/SheetTabBar/SheetTab.tsx
Hi there,
Changed another menu so all look the same. Find below the change:
Before:
After:
Best,
D
=> FIX: Made menu on SheetTab consistent with Figmas

webapp/src/components/toolbar.tsx
Hi again,
I made some changes in the toolbox. I'm listing them below:
- Adjusted hover, pressed and disabled states
- Changed border colors and radii
- Made icon colors consistent
- Buttons don't stretch anymore on mobile
- Fixed spacing between items so it looks as expected
- Replaced hex color with theme colors
- Replaced PaintBrush icon for PaintRoller (was recently added to Lucide's library)
Before:
After:
Best,
D
=> FIX: Several cosmetic changes to make the toolbar look like the figmas

webapp/src/components/SheetTabBar/SheetTab.tsx, webapp/src/components/SheetTabBar/SheetTabBar.tsx
Hey there,
I've made a few more changes in the Sheet Navigator:
Functionality:
- Double-clicking on the sheet name prompts the rename sheet dialog
Accessibility:
- Active tabs have a background color now. Open sheets that use emojis as sheet name are easier to spot
Cosmetics:
- Got rid of all hex colors – now we only use the theme in these 2 files
- Fixed a bunch of paddings, gaps and margins
- Tiny transition effect on hover
---
Before:
After:
Let me know what you think!
D
=> UPDATE: Better active states on Sheet Nav + Double click to rename sheets

webapp/src/components/borderPicker.tsx, webapp/src/icons/border-style.svg
Hi!
Super late PR 😅 but had to fix one more menu.
I've made the usual padding/margin/spacing/etc changes plus cleaned things up a bit (use theme styles instead of hex colors, replaced an outdated icon and reordered somethings so we don't have buttons inside buttons). See the difference below, as usual:
Before:
After:
Cheers,
D
=> FIX: Border picker cosmetics

webapp/src/components/SheetTabBar/SheetRenameDialog.tsx
This will be a standard "Prompt" widget
* ESC closes the dialog without changes
* Can copy/cut paste
=> FIX[UI]: Rename modal dialog fixes

webapp/src/components/WorksheetCanvas/constants.ts
Column headers in IronCalc were using the wrong color (a shade of blue instead of a shade of grey).
Before:
After:
I know this is super hard to notice for some people and in some displays but as it's a small change I thought it'd be good to get it done now 🙂.
Best,
D
=> FIX: make grid header colors consistent

webapp/src/AppComponents/DeleteWorkbookDialog.tsx, webapp/src/AppComponents/FileMenu.tsx
This PR introduces a confirmation modal that appears when a user clicks "Delete Workbook" in the File Menu. See below how it looks:
Users reported accidentally deleting workbooks without a clear way to confirm or cancel the action.
Let me know what you think or if we need additional changes!
Best,
D
=> UPDATE: Add confirmation modal for deleting workbooks

base/src/model.rs, base/src/test/user_model/mod.rs, base/src/test/user_model/test_sheet_state.rs, base/src/user_model/common.rs, base/src/user_model/history.rs, bindings/wasm/src/lib.rs, bindings/wasm/types.ts, webapp/src/components/SheetTabBar/SheetListMenu.tsx, webapp/src/components/SheetTabBar/SheetTab.tsx, webapp/src/components/SheetTabBar/SheetTabBar.tsx, webapp/src/components/SheetTabBar/types.ts, webapp/src/components/workbook.tsx
This implements hide/unhide sheets in the UI and bindings
There are some corner cases that are not treated correctly:
1. Hide sheet
2. Unhide sheet and select it
3. Undo
The you end up in a selected sheet that is hidden.
You probably will want to change some stuff later:
=> UPDATE: Hide/Unhide sheets

webapp/src/components/workbook.tsx
Hi @nhatcher,
We recently updated the 'Copy/Paste Format' icon in the toolbar but we still had the old one as a cursor, after clicking the button. So here's my attempt to fix that. 
In the video below you can see the before/after:
https://github.com/user-attachments/assets/c4656abc-0112-4095-8e98-d068921a78a0
Let me know if this is the right way of doing it, of if there's maybe a 'cleaner' way.
Thanks!
D
=> FIX: Use the right icon for paste format action

webapp/src/AppComponents/UploadFileDialog.tsx, webapp/src/components/SheetTabBar/SheetRenameDialog.tsx, webapp/src/components/formatPicker.tsx, webapp/src/locale/en_us.json
Hi there,
This PR replaces the custom 'X' svg icons with the Lucide icon library in all dialogs.
Best,
D
=> FIX: Replace SVG "X" icons with Lucide icons for consistency in dialogs

base/src/calc_result.rs, base/src/expressions/parser/mod.rs, base/src/expressions/parser/move_formula.rs, base/src/expressions/parser/stringify.rs, base/src/expressions/parser/tests/test_general.rs, base/src/expressions/parser/tests/test_issue_155.rs, base/src/expressions/parser/tests/test_move_formula.rs, base/src/expressions/parser/tests/test_ranges.rs, base/src/expressions/parser/tests/test_stringify.rs, base/src/expressions/parser/tests/test_tables.rs, base/src/expressions/parser/walk.rs, base/src/functions/information.rs, base/src/lib.rs, base/src/model.rs, base/src/new_empty.rs, base/src/test/user_model/mod.rs, base/src/test/user_model/test_defined_names.rs, base/src/test/user_model/test_general.rs, base/src/units.rs, base/src/user_model/common.rs, base/src/user_model/history.rs, base/src/workbook.rs, bindings/wasm/fix_types.py, bindings/wasm/src/lib.rs, bindings/wasm/types.ts, xlsx/src/import/worksheets.rs
This adds a 'user'  API for defined names (Add/Delete/Update) with undo/redo history support.
In the AST (Abstract Syntax Tree) I split the VariableKind node into three different nodes:
* DefinedNameKind that holds also the scope of the defined name
* TableNameKind
* WrongVariableKind
So at parse time we have much more information.
Also renaming a defined name is a bit tricky so there is a bit of code for that following suit of the rename_sheet method
=> UPDATE: API for defined names

base/src/expressions/parser/mod.rs, base/src/functions/logical.rs, base/src/functions/mod.rs, base/src/test/mod.rs, base/src/test/test_true_false.rs
Previously the engine was internally transforming TRUE() to TRUE
Note that the friendly giant implements this only for compatibility reasons
=> FIX: TRUE and FALSE can also be functions

docs/src/.vitepress/config.mts, docs/src/web-application/name-manager.md
This is a bit tough, there is not yet a good place to add documentation about dialogs in the widget.
We have the general documentation of the engine. All those things are valid everywhere IronCalc is used. Could be from the web or an scripting language like Python.
We have the documentation of the Web Application deployed at app.ironcalc.com. These are things like export/import and sharing features that are not related to the spreadsheet widget.
Finally we have the documentation of dialogs (like this one) in the widget. Those will be used wherever the widget is used, non necessarily in our own service.
FYI: @dg-ac , @aloifran , @stevethesleeve
=> FIX: Add link to name manager page

webapp/src/components/NameManagerDialog/NameManagerDialog.tsx, webapp/src/components/NameManagerDialog/NamedRangeActive.tsx, webapp/src/components/NameManagerDialog/NamedRangeInactive.tsx, webapp/src/locale/en_us.json
Hi there,
I've been making a few cosmetic adjustments to the new Name Manager. What we have is great as a first version and works quite well, however I thought some design adjustments were needed. Besides, now it can be used on mobile devices. 
So, in summary, I have:
1. Changed a bunch of borders, margins, paddings, etc to improve the layout
2. Improved accessibility on action buttons by increasing icon sizes, adding hover style and tooltips
3. Adjusted header and footer to make it consistent with the other dialogs
4. Adjusted the dialog so it can be used on mobile devices
Before:
After:
Regarding the mobile view, it still needs to improve a lot, but at least is usable. Next step here would be to get back to Figma and design a proper mobile version of this dialog.
I would also like to …
=> FIX: Name Manager cosmetics and responsiveness

docs/src/contributing/how-to-contribute.md
This PR fixes the Discord invite link we had in the '[How to Contribute](https://docs.ironcalc.com/contributing/how-to-contribute.html)', in the Documentation, which was broken.
=> FIX: Wrong Discord invite link

base/src/user_model/common.rs, xlsx/tests/test.rs
=> UPDATE: Exposes the model in UserModel

webapp/IronCalc/src/components/SheetTabBar/SheetTabBar.tsx, webapp/IronCalc/src/components/formatPicker.tsx, webapp/IronCalc/src/components/formulabar.tsx
Hi,
I've fixed/improved a few things that were a bit annoying in the mobile view:
1. Removed ironcalc.com link: this was using too much horizontal space in the sheet container, hurting usability\
2. Input on formatPicker was longer than dialog
3. On formula bar, I've reduced the excessive distance between selected cell and the divider
4. Updated hex colors to use the theme ones
Let me know if I need to change anything.
Best,
D
=> Update: Mobile improvements

webapp/IronCalc/src/components/NameManagerDialog/NameManagerDialog.tsx, webapp/IronCalc/src/locale/en_us.json
Hi there,
This low-p PR adds an empty state to the Name Manager dialog to improve accessibility and avoid blank spaces when no named ranges are present.
Should look like this one:
Best,
D
=> UPDATE: Add an empty state message to the Name Manager

webapp/IronCalc/src/components/WorksheetCanvas/worksheetCanvas.ts
This fixes a bug where if you were wrapping text,
the first word was repeated.
We really need tests!
=> FIX: Wrap text properly

webapp/IronCalc/src/components/Workbook/Workbook.tsx
We were previously downloading only the bounds of the visible cells, without taking into account the frozen rows/colums.
Fixes #343
=> FIX: Download all selected area

base/src/test/test_styles.rs, base/src/types.rs
Excel expects two default fills. If a different fill is present Excel removes it and substitutes it with the defaults.
This resulted in models having the default fill for the first style.
Thanks @scandel!
=> FIX: There are two fills in every new Excel model

xlsx/src/import/styles.rs
I would like to have a text case for this. Preferably automatic.
But manual is ok, maybe we should have a series of workbooks we check before every large deployment
=> FIX[import]: Set color black for text properly

webapp/IronCalc/src/components/Toolbar/Toolbar.tsx, webapp/IronCalc/src/icons/decrease-decimal.svg, webapp/IronCalc/src/icons/increase-decimal.svg
This PR replaces the current `remove decimal` and `increase decimal` icons in the widget. Until now we were using custom-made icons but since Lucide has added [similar ones](https://lucide.dev/icons/?search=decimal) to their library, it's better to use these.
`before`
`after`
=> update: replace custom made icons with lucide's

webapp/IronCalc/src/components/Toolbar/Toolbar.tsx
This PR fixes a visual bug in the Type and Cell background color buttons, in the webapp's toolbar:
This was specially visible in mobile devices.
After the fix, it should look like here below:
=> fix: corners in Type and Cell background color buttons

webapp/app.ironcalc.com/frontend/src/components/FileBar.tsx, webapp/app.ironcalc.com/frontend/src/components/FileMenu.tsx, webapp/app.ironcalc.com/frontend/src/components/HelpMenu.tsx
This PR introduces a small change in the file bar of the app by adding a new menu for the Help button, which until now it was just opening the documentation.
The update avoids confusion caused by accidental clicking (as it was just opening a new tab which was very sudden). In the future we should add other items to this menu and maybe place the shortcuts in its own dialog, instead of just relying in the Docs.
=> update: add a Help menu to App

README.md
Since https://github.com/ironcalc/IronCalc/pull/27, using `base::model::Model` complains about `model` being a private module, and `base::Model` should be used instead.
=> Fix example in README to reference Model correctly.
