ironcalc/IronCalc

base/src/test/engineering/test_complex.rs

See previous discussion in:
https://github.com/ironcalc/IronCalc/pull/19

FIX: Fixes incorrect result in M1 Apple silicom

---

base/src/test/user_model/mod.rs
base/src/test/user_model/test_autofill.rs
base/src/user_model.rs
bindings/wasm/src/lib.rs
bindings/wasm/tests/test.mjs

Still missing by columns and there is no "predictive" autofill 1,2,3 => 4,5,6

UPDATE: Autofill by rows

---

bindings/wasm/fix_types.py

We really need a better way of doing this :/

FIX: Fixes TypeScript types correctly

---

README.md

FIX: Removes comment about needing a logo in the README.md

---

xlsx/src/import/mod.rs
xlsx/tests/test.rs

This is usefull if we are transfering bytes, for instance over the internet

UPDATE: Adds `load_from_xlsx_bytes`

---

webapp/src/App.tsx

Note that previously the model would have been fetched twice

FIX[WebApp]: Simplify loading logic of workbook

---

webapp/src/AppComponents/FileBar.tsx
webapp/src/AppComponents/ShareButton.tsx
webapp/src/components/borderPicker.tsx
webapp/src/components/navigation/menus.tsx
webapp/src/components/navigation/navigation.tsx
webapp/src/components/navigation/sheet.tsx
webapp/src/icons/border-style.svg

* Toast has Inter font-family
* Share button has Inter font family
* More accurate menu list to design
* Removes unused navigation
* Adds link to IronCalc
* Removes line=black :O

FIX: Several UI fixes from Dani

---

webapp/src/locale/en_us.json

Added navigation labels for sheet management in en_us.json (this is my first pull request on Github, ever)

Adds navigation labels for sheet management

---

CHANGELOG.md

UPDATE: Add entry in CHANGELOG for UNICODE function

---

CONTRIBUTING.md

This PR is dual purpose.
1. It proposes several minor improvements to the recently written contributing guide. These have been identified while following the guide to prepare my local computer for producing docs. I have implemented and previewed the revised document in VSCode (installing the documentation server is the next item on my to-do list).
2. It is my first IronCalc PR.

Minor improvements to CONTRIBUTING.md

---

webapp/src/AppComponents/UploadFileDialog.tsx

@nhatcher Another PR with very small updates:
- Makes the link to documentation usable
- Changes a few tiny bits so the implementation is closer to what we had in the Figma mockups
Let me know if this works for you.
D

UPDATE: Small fixes in Upload file Dialog

---

bindings/python/src/lib.rs
bindings/python/src/types.rs

adding accessibility to more cell api

added missing api functions for get_cell*

---

webapp/src/AppComponents/FileBar.tsx
webapp/src/AppComponents/FileMenu.tsx

Hi @nhatcher,
Small update here. Based on our Figmas, I'm adding a new button to the top bar of the webapp, this time leading to our recently released Docs. LEt me know what you think!
D

UPDATE: Added a 'Help' button in the top header that leads to the docs

---

.github/workflows/test-coverage.yaml

This is a bit unfortunate, but until this can run reliably this is mostly noise.
I have send them an email, maybe I can fix this.

FIX: Disable coverage as it is failing for all

---

webapp/src/components/colorPicker.tsx
webapp/src/components/workbook.tsx

Hey there,
I've made some small cosmetic changes in the color picker. See below the before/after:
Before:
After:
Best,
D

UPDATE: Color picker changes

---

CHANGELOG.md
base/src/test/test_column_width.rs
base/src/test/test_general.rs
base/src/worksheet.rs
webapp/src/components/worksheet.tsx

FIX: Prevent negative column width, row height

---

webapp/src/components/navigation/navigation.tsx

Hi @nhatcher,
Tiny change here, as discussed on #180.
Thanks,
D

FIX: remove legacy scrollbar styles

---

webapp/src/components/formatMenu.tsx

Hi @nhatcher,
Thanks for the comments before in #179. I've made here the requested changes in the format menu.
Let me know what you think.
Thanks

FIX: Replace inline styles with StyledMenu component for improved readability

---

base/src/test/user_model/test_paste_csv.rs
base/src/user_model/common.rs
bindings/wasm/fix_types.py
bindings/wasm/src/lib.rs
webapp/src/components/workbook.tsx

Fixes #193
FYI @enjoythecode 
Feel free to review :)

FIX: When cut and paste to a different sheet origin is removed

---

webapp/src/AppComponents/DeleteWorkbookDialog.tsx
webapp/src/AppComponents/FileMenu.tsx
webapp/src/AppComponents/UploadFileDialog.tsx

Hi @dg-ac,
Some minor changes hopefully they are self-evident.

FIX[WebApp]: Some fixes to the DeleteWorkbook and Import dialogs

---

bindings/wasm/Makefile

FIX: Removes types.js after used

---

webapp/src/components/borderPicker.tsx

FIX: The default border color should be black

---

base/src/constants.rs
base/src/formatter/dates.rs
base/src/formatter/format.rs
base/src/functions/date_and_time.rs
base/src/functions/financial.rs
base/src/test/test_date_and_time.rs

FYI: @stevethesleeve, this corresponds to your documentation

FIX: Use 1 as the first serial number corresponding to 1899-12-31

---

webapp/src/AppComponents/UploadFileDialog.tsx
webapp/src/components/SheetTabBar/SheetRenameDialog.tsx
webapp/src/components/formatPicker.tsx

Hey there,
This PR intends to fix some issues and inconsistencies in our dialogs. Before, hitting the key Tab on dialogs would also select the content behind. That should be fixed now. 
Best,
D

UPDATE: Dialog fixes

---

webapp/IronCalc/src/components/formatPicker.tsx

Fixes #240
It is a pity we have to do this. There probably is a better way

FIX: Can cut and paste in Custom Format Dialog

---

webapp/IronCalc/src/components/SheetTabBar/SheetDeleteDialog.tsx
webapp/IronCalc/src/components/SheetTabBar/SheetTab.tsx
webapp/IronCalc/src/locale/en_us.json

Hi,
This PR introduces a confirmation dialog to prevent accidental deletion of sheets and potential data loss. To see it, click on the chevron icon and then on 'Delete':
After that, a the dialog like this one that should appear.
Thanks,
D

UPDATE: Deleting a sheet prompts a confirmation dialog

---

docs/src/features/unsupported-features.md
docs/src/web-application/name-manager.md

Hi there,
Since we added the Name Manager a couple of weeks ago, I thought it was time to also complete its respective page in the Documentation, as at the moment we only had some placeholder text.
I'm also planning to add some images or videos to this and the other pages soon.
Best,
D

UPDATE: Name Manager page

---

base/src/test/user_model/test_styles.rs
base/src/user_model/common.rs
base/src/user_model/history.rs
bindings/nodejs/src/user_model.rs
bindings/wasm/src/lib.rs
webapp/IronCalc/src/components/toolbar.tsx
webapp/IronCalc/src/components/workbook.tsx
webapp/IronCalc/src/locale/en_us.json

UPDATE: Add clear formatting

---

webapp/IronCalc/package-lock.json
webapp/IronCalc/package.json
webapp/IronCalc/src/components/SheetTabBar/SheetTab.tsx
webapp/IronCalc/src/components/borderPicker.tsx
webapp/IronCalc/src/components/colorPicker.tsx
webapp/IronCalc/src/components/editor/useKeyDown.ts
webapp/IronCalc/src/components/editor/util.tsx
webapp/IronCalc/src/components/useKeyboardNavigation.ts
webapp/IronCalc/src/components/usePointer.ts
webapp/IronCalc/src/components/workbook.tsx
webapp/app.ironcalc.com/frontend/package-lock.json
webapp/app.ironcalc.com/frontend/package.json
webapp/app.ironcalc.com/frontend/src/components/DeleteWorkbookDialog.tsx
webapp/app.ironcalc.com/frontend/src/components/FileMenu.tsx
webapp/app.ironcalc.com/frontend/src/components/UploadFileDialog.tsx

UPDATE: Update to React 19.0.0

---

base/src/test/user_model/mod.rs
base/src/test/user_model/test_add_delete_sheets.rs
base/src/test/user_model/test_sheets_undo_redo.rs
base/src/user_model/common.rs
base/src/user_model/history.rs
webapp/IronCalc/src/locale/en_us.json

Now we can undo adding or deleting worksheets
FYI: @dg-ac

FIX: Undo/redo delete/add page

---

webapp/IronCalc/src/components/CellContextMenu.tsx

Hi there,
I've made some minimal changes in the new cell contextual menus. This is to make them consistent with other menus in the application.
Besides, I've replaced the hex colors with them colors.
Best,
D

UPDATE: Style changes in new contextual menus

---

webapp/IronCalc/src/components/WorksheetCanvas/worksheetCanvas.ts

Also draws the lines at the correct position

FIX: Shows borders correctly in case of frozen rows.

---

webapp/app.ironcalc.com/Caddyfile

FIX: Adds localhost in the development server Caddyfile

---

webapp/IronCalc/src/components/workbook.tsx

This clearly shows we need beter testing in the frontend

FIX: Control+B,I,U work again

---

webapp/IronCalc/src/components/ColorPicker.tsx
webapp/IronCalc/src/components/SheetTabBar/SheetTab.tsx
webapp/IronCalc/src/components/borderPicker.tsx
webapp/IronCalc/src/components/toolbar.tsx
webapp/IronCalc/src/locale/en_us.json

Hey Dani, this adds a much needed button to the color picker

FIX: Add "Apply" button to color picker

---

webapp/app.ironcalc.com/frontend/package-lock.json
webapp/app.ironcalc.com/frontend/package.json
webapp/app.ironcalc.com/frontend/src/components/FileBar.tsx
webapp/app.ironcalc.com/frontend/src/components/ShareWorkbookDialog.tsx

This is @dg-ac 's work from #311

UPDATE: Add a dialog when 'Share' buttons is clickled

---

webapp/IronCalc/src/components/Toolbar/Toolbar.tsx
webapp/IronCalc/src/components/Workbook/Workbook.tsx
webapp/IronCalc/src/components/WorksheetCanvas/worksheetCanvas.ts
webapp/IronCalc/src/locale/en_us.json

FIX: More sensible decrease/increase font-size

---

webapp/app.ironcalc.com/frontend/src/components/FileBar.tsx
webapp/app.ironcalc.com/frontend/src/components/WorkbookTitle.tsx

Hi Dani, in this PR:
- Add `useWindowWidth` hook to track and update window width on resize.
- Introduce `maxWidth` prop to `WorkbookTitle` for responsive truncation.
- Replace hidden text element with an editable `input` controlled by a mirror `div` for measuring width.
- Position the title absolutely in `FileBar` and use a spacer to keep it centered.
- Allow pressing “Enter” to commit name changes and “Escape” to revert them.

FIX[app.ironcalc.com]: Clean up code for the title

---

webapp/IronCalc/src/components/Toolbar/Toolbar.tsx

Hi there,
This PR intends to remove some unused comments and attributes from the new color picker.
Thanks,
D
cc @nhatcher

FIX: Cleanup code on new color picker

---

Cargo.lock
bindings/wasm/Cargo.toml
bindings/wasm/fix_types.py
bindings/wasm/src/lib.rs

https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/unchecked_type.html

feat: use wasm-bindgen unchecked_return_type

---

webapp/app.ironcalc.com/frontend/src/components/rpc.ts

FIX[webapp]: Allow downloading workbooks with unicode charaters

---

base/src/user_model/common.rs

FIX: Removing styles of full columns or rows are a single diff list

---

webapp/IronCalc/src/components/util.ts

This is a "Hot Fix". A proper fix should use the wasm module
FYI: @dg-ac

FIX: Quote sheet names properly

---

webapp/IronCalc/src/components/Worksheet/usePointer.ts

FIX: Checks also that the sheet is the same

---

webapp/IronCalc/src/components/Editor/Editor.tsx

FIX: stop propagation on copy in the editor

---

base/src/user_model/ui.rs
bindings/wasm/src/lib.rs
webapp/IronCalc/src/components/Workbook/Workbook.tsx
webapp/IronCalc/src/components/Workbook/useKeyboardNavigation.ts

This was a left over from the old days
Control+right arrow takes you to the next cell with text or the end of the block
NB: Missing tests

FIX: Adds sheet "block" navigation

---

base/src/actions.rs
base/src/test/user_model/mod.rs
base/src/test/user_model/test_batch_row_column_diff.rs
base/src/test/user_model/test_diff_queue.rs
base/src/test/user_model/test_general.rs
base/src/test/user_model/test_multi_row_column.rs
base/src/test/user_model/test_row_column.rs
base/src/user_model/common.rs
base/src/user_model/history.rs
base/src/user_model/mod.rs
bindings/nodejs/index.d.ts
bindings/nodejs/src/user_model.rs
bindings/wasm/src/lib.rs
bindings/wasm/tests/test.mjs
webapp/IronCalc/src/components/Worksheet/Worksheet.tsx

feat: insert delete rows cols
